name: Run clean.py on push

on: [push]

jobs:
 run-clean:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run clean.py
      run: python clean.py
    
    - name: Check clean.py output
      run: test -f data/clean/data_cleaned.csv

    - name: Run transform.py
      run: python transform.py
    
    - name: Check transform.py output
      run: test -f data/transformed/data_transformed.csv

    - name: Run load.py
      run: python load.py

    - name: Check load.py output
      run: test -f data/final/final_output.csv


