name: Run clean.py on push

on: [push]

jobs:
 run-clean:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run clean.py
      run: python clean.py

    - name: Run transform.py
      run: python transform.py


